-- Atsiitsʼiin Snowflake schema

CREATE TABLE IF NOT EXISTS NOTES (
  ID VARCHAR PRIMARY KEY,
  USER_ID VARCHAR,
  SOURCE VARCHAR,
  TITLE VARCHAR,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE TABLE NOTE_CHUNKS (
  ID VARCHAR PRIMARY KEY,
  NOTE_ID VARCHAR,
  CHUNK_INDEX INT,
  TEXT STRING,
  EMBEDDING VARIANT,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
);

-- Example similarity query
-- SELECT ID, NOTE_ID, CHUNK_INDEX, TEXT,
--        1 - VECTOR_COSINE_SIMILARITY(EMBEDDING, :query_embedding) AS distance
-- FROM NOTE_CHUNKS
-- ORDER BY distance ASC
-- LIMIT 10;

CREATE TABLE IF NOT EXISTS TAGS (
  TAG VARCHAR PRIMARY KEY,
  DISPLAY_NAME VARCHAR,
  DESCRIPTION STRING,
  COLOR_HEX VARCHAR(7),
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS NOTE_TAGS (
  NOTE_ID VARCHAR REFERENCES NOTES(ID),
  TAG VARCHAR REFERENCES TAGS(TAG),
  SOURCE VARCHAR DEFAULT 'llm_suggestion',
  CONFIDENCE FLOAT,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP_NTZ,
  PRIMARY KEY (NOTE_ID, TAG)
);

CREATE TABLE IF NOT EXISTS NOTE_TAG_AUDIT (
  AUDIT_ID VARCHAR PRIMARY KEY,
  NOTE_ID VARCHAR REFERENCES NOTES(ID),
  TAGS VARIANT,
  RAW_RESPONSE VARIANT,
  SOURCE VARCHAR DEFAULT 'llm_suggestion',
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
);

-- Grant all permissions to MS3DM_ACCOUNT_ADMIN role
GRANT ALL PRIVILEGES ON TABLE MS3DM.ATSIITSIIN.NOTES TO ROLE MS3DM_ACCOUNT_ADMIN;
GRANT ALL PRIVILEGES ON TABLE MS3DM.ATSIITSIIN.NOTE_CHUNKS TO ROLE MS3DM_ACCOUNT_ADMIN;
GRANT ALL PRIVILEGES ON TABLE MS3DM.ATSIITSIIN.TAGS TO ROLE MS3DM_ACCOUNT_ADMIN;
GRANT ALL PRIVILEGES ON TABLE MS3DM.ATSIITSIIN.NOTE_TAGS TO ROLE MS3DM_ACCOUNT_ADMIN;
GRANT ALL PRIVILEGES ON TABLE MS3DM.ATSIITSIIN.NOTE_TAG_AUDIT TO ROLE MS3DM_ACCOUNT_ADMIN;
GRANT USAGE ON DATABASE MS3DM TO ROLE MS3DM_ACCOUNT_ADMIN;
GRANT USAGE ON SCHEMA MS3DM.ATSIITSIIN TO ROLE MS3DM_ACCOUNT_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA MS3DM.ATSIITSIIN TO ROLE MS3DM_ACCOUNT_ADMIN;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA MS3DM.ATSIITSIIN TO ROLE MS3DM_ACCOUNT_ADMIN;
GRANT ALL PRIVILEGES ON WAREHOUSE COMPUTE_WH TO ROLE MS3DM_ACCOUNT_ADMIN;


