-- Snowflake schema adjustments for context classification

-- Add context fields to NOTES table if they do not exist
ALTER TABLE IF EXISTS NOTES ADD COLUMN IF NOT EXISTS CONTEXT_LABEL STRING;
ALTER TABLE IF EXISTS NOTES ADD COLUMN IF NOT EXISTS CONTEXT_CONFIDENCE FLOAT;
ALTER TABLE IF EXISTS NOTES ADD COLUMN IF NOT EXISTS CONTEXT_ANALYZED_AT TIMESTAMP_NTZ;

-- Worklog table to track processing runs
CREATE TABLE IF NOT EXISTS NOTE_CONTEXT_WORKLOG (
    WORKLOG_ID STRING DEFAULT UUID_STRING(),
    NOTE_ID STRING,
    STATUS STRING,
    CONTEXT_LABEL STRING,
    CONTEXT_CONFIDENCE FLOAT,
    ERROR_MESSAGE STRING,
    ANALYZED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (WORKLOG_ID)
);

